version: '3.2'
services: 
    main-service:
        container_name: main-service
        image: green/main-service:1.0.0-SNAPSHOT
        ports:
            - 8080:8080
        environment:
            - APP_PORT=8080
            - HOST_URL=192.168.0.108
        networks:
            - services
            
    timesheet-service:
        container_name: timesheet-service
        image: green/timesheet-service:1.0.0-SNAPSHOT
        ports:
            - 8070:8070
        environment:
            - APP_PORT=8070
            - HOST_URL=192.168.0.108
        networks:
            - services            
            
networks: 
    services:
        driver: bridge
