global:
    scrape_interval:     15s # By default, scrape targets every 15 seconds.

    # tag::adocPrometheus[]
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'consul-prometheus'
    metrics_path: '/q/metrics'
    consul_sd_configs:
      - server: '192.168.0.103:8500'
        services: []      
# end::adocPrometheus[]
